//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorePlus.WeiXin.Service.ServantService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CorePlus.WeiXin.Service.ServantService.UserEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity))]
    public partial class UserEntity : CorePlus.WeiXin.Service.ServantService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPwdField;
        
        private System.Nullable<long> RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPwd {
            get {
                return this.UserPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPwdField, value) != true)) {
                    this.UserPwdField = value;
                    this.RaisePropertyChanged("UserPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServantInfoEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServantInfoEntity : CorePlus.WeiXin.Service.ServantService.UserEntity {
        
        private System.Nullable<long> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeiXinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ChnName {
            get {
                return this.ChnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChnNameField, value) != true)) {
                    this.ChnNameField = value;
                    this.RaisePropertyChanged("ChnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WeiXinNo {
            get {
                return this.WeiXinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeiXinNoField, value) != true)) {
                    this.WeiXinNoField = value;
                    this.RaisePropertyChanged("WeiXinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OpenId {
            get {
                return this.OpenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIdField, value) != true)) {
                    this.OpenIdField = value;
                    this.RaisePropertyChanged("OpenId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServantService.ServantServiceSoap")]
    public interface ServantServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByOwner", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.GetByOwnerResponse GetByOwner(CorePlus.WeiXin.Service.ServantService.GetByOwnerRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 openId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByOpenId", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.GetByOpenIdResponse GetByOpenId(CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 openid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWeiXin", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.UpdateWeiXinResponse UpdateWeiXin(CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.LoginResponse Login(CorePlus.WeiXin.Service.ServantService.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByUserName", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.GetByUserNameResponse GetByUserName(CorePlus.WeiXin.Service.ServantService.GetByUserNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.AddResponse Add(CorePlus.WeiXin.Service.ServantService.AddRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.UpdateResponse Update(CorePlus.WeiXin.Service.ServantService.UpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.DeleteResponse Delete(CorePlus.WeiXin.Service.ServantService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteById", ReplyAction="*")]
        bool DeleteById(long id);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.GetAllResponse GetAll(CorePlus.WeiXin.Service.ServantService.GetAllRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetByIdResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        CorePlus.WeiXin.Service.ServantService.GetByIdResponse GetById(CorePlus.WeiXin.Service.ServantService.GetByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByOwner", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByOwnerRequestBody Body;
        
        public GetByOwnerRequest() {
        }
        
        public GetByOwnerRequest(CorePlus.WeiXin.Service.ServantService.GetByOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string owner;
        
        public GetByOwnerRequestBody() {
        }
        
        public GetByOwnerRequestBody(string id, string owner) {
            this.id = id;
            this.owner = owner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByOwnerResponseBody Body;
        
        public GetByOwnerResponse() {
        }
        
        public GetByOwnerResponse(CorePlus.WeiXin.Service.ServantService.GetByOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByOwnerResult;
        
        public GetByOwnerResponseBody() {
        }
        
        public GetByOwnerResponseBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByOwnerResult) {
            this.GetByOwnerResult = GetByOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByOpenIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByOpenId", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequestBody Body;
        
        public GetByOpenIdRequest() {
        }
        
        public GetByOpenIdRequest(CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByOpenIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openId;
        
        public GetByOpenIdRequestBody() {
        }
        
        public GetByOpenIdRequestBody(string openId) {
            this.openId = openId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByOpenIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByOpenIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByOpenIdResponseBody Body;
        
        public GetByOpenIdResponse() {
        }
        
        public GetByOpenIdResponse(CorePlus.WeiXin.Service.ServantService.GetByOpenIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByOpenIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByOpenIdResult;
        
        public GetByOpenIdResponseBody() {
        }
        
        public GetByOpenIdResponseBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByOpenIdResult) {
            this.GetByOpenIdResult = GetByOpenIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWeiXinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWeiXin", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequestBody Body;
        
        public UpdateWeiXinRequest() {
        }
        
        public UpdateWeiXinRequest(CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWeiXinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string openid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string weixinno;
        
        public UpdateWeiXinRequestBody() {
        }
        
        public UpdateWeiXinRequestBody(long id, string openid, string weixinno) {
            this.id = id;
            this.openid = openid;
            this.weixinno = weixinno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWeiXinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWeiXinResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.UpdateWeiXinResponseBody Body;
        
        public UpdateWeiXinResponse() {
        }
        
        public UpdateWeiXinResponse(CorePlus.WeiXin.Service.ServantService.UpdateWeiXinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWeiXinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateWeiXinResult;
        
        public UpdateWeiXinResponseBody() {
        }
        
        public UpdateWeiXinResponseBody(bool UpdateWeiXinResult) {
            this.UpdateWeiXinResult = UpdateWeiXinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(CorePlus.WeiXin.Service.ServantService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginPwd;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string loginName, string loginPwd) {
            this.loginName = loginName;
            this.loginPwd = loginPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(CorePlus.WeiXin.Service.ServantService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByUserName", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByUserNameRequestBody Body;
        
        public GetByUserNameRequest() {
        }
        
        public GetByUserNameRequest(CorePlus.WeiXin.Service.ServantService.GetByUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetByUserNameRequestBody() {
        }
        
        public GetByUserNameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByUserNameResponseBody Body;
        
        public GetByUserNameResponse() {
        }
        
        public GetByUserNameResponse(CorePlus.WeiXin.Service.ServantService.GetByUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByUserNameResult;
        
        public GetByUserNameResponseBody() {
        }
        
        public GetByUserNameResponseBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByUserNameResult) {
            this.GetByUserNameResult = GetByUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(CorePlus.WeiXin.Service.ServantService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(CorePlus.WeiXin.Service.ServantService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(long AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(CorePlus.WeiXin.Service.ServantService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(CorePlus.WeiXin.Service.ServantService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(CorePlus.WeiXin.Service.ServantService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(CorePlus.WeiXin.Service.ServantService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(bool DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(CorePlus.WeiXin.Service.ServantService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(CorePlus.WeiXin.Service.ServantService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByIdRequestBody Body;
        
        public GetByIdRequest() {
        }
        
        public GetByIdRequest(CorePlus.WeiXin.Service.ServantService.GetByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetByIdRequestBody() {
        }
        
        public GetByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.WeiXin.Service.ServantService.GetByIdResponseBody Body;
        
        public GetByIdResponse() {
        }
        
        public GetByIdResponse(CorePlus.WeiXin.Service.ServantService.GetByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByIdResult;
        
        public GetByIdResponseBody() {
        }
        
        public GetByIdResponseBody(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByIdResult) {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServantServiceSoapChannel : CorePlus.WeiXin.Service.ServantService.ServantServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServantServiceSoapClient : System.ServiceModel.ClientBase<CorePlus.WeiXin.Service.ServantService.ServantServiceSoap>, CorePlus.WeiXin.Service.ServantService.ServantServiceSoap {
        
        public ServantServiceSoapClient() {
        }
        
        public ServantServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServantServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServantServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServantServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.GetByOwnerResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.GetByOwner(CorePlus.WeiXin.Service.ServantService.GetByOwnerRequest request) {
            return base.Channel.GetByOwner(request);
        }
        
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByOwner(string id, string owner) {
            CorePlus.WeiXin.Service.ServantService.GetByOwnerRequest inValue = new CorePlus.WeiXin.Service.ServantService.GetByOwnerRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.GetByOwnerRequestBody();
            inValue.Body.id = id;
            inValue.Body.owner = owner;
            CorePlus.WeiXin.Service.ServantService.GetByOwnerResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).GetByOwner(inValue);
            return retVal.Body.GetByOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.GetByOpenIdResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.GetByOpenId(CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequest request) {
            return base.Channel.GetByOpenId(request);
        }
        
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByOpenId(string openId) {
            CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequest inValue = new CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.GetByOpenIdRequestBody();
            inValue.Body.openId = openId;
            CorePlus.WeiXin.Service.ServantService.GetByOpenIdResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).GetByOpenId(inValue);
            return retVal.Body.GetByOpenIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.UpdateWeiXinResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.UpdateWeiXin(CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequest request) {
            return base.Channel.UpdateWeiXin(request);
        }
        
        public bool UpdateWeiXin(long id, string openid, string weixinno) {
            CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequest inValue = new CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.UpdateWeiXinRequestBody();
            inValue.Body.id = id;
            inValue.Body.openid = openid;
            inValue.Body.weixinno = weixinno;
            CorePlus.WeiXin.Service.ServantService.UpdateWeiXinResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).UpdateWeiXin(inValue);
            return retVal.Body.UpdateWeiXinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.LoginResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.Login(CorePlus.WeiXin.Service.ServantService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity Login(string loginName, string loginPwd) {
            CorePlus.WeiXin.Service.ServantService.LoginRequest inValue = new CorePlus.WeiXin.Service.ServantService.LoginRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.loginPwd = loginPwd;
            CorePlus.WeiXin.Service.ServantService.LoginResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.GetByUserNameResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.GetByUserName(CorePlus.WeiXin.Service.ServantService.GetByUserNameRequest request) {
            return base.Channel.GetByUserName(request);
        }
        
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetByUserName(string username) {
            CorePlus.WeiXin.Service.ServantService.GetByUserNameRequest inValue = new CorePlus.WeiXin.Service.ServantService.GetByUserNameRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.GetByUserNameRequestBody();
            inValue.Body.username = username;
            CorePlus.WeiXin.Service.ServantService.GetByUserNameResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).GetByUserName(inValue);
            return retVal.Body.GetByUserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.AddResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.Add(CorePlus.WeiXin.Service.ServantService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public long Add(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity) {
            CorePlus.WeiXin.Service.ServantService.AddRequest inValue = new CorePlus.WeiXin.Service.ServantService.AddRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.AddRequestBody();
            inValue.Body.entity = entity;
            CorePlus.WeiXin.Service.ServantService.AddResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.UpdateResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.Update(CorePlus.WeiXin.Service.ServantService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity) {
            CorePlus.WeiXin.Service.ServantService.UpdateRequest inValue = new CorePlus.WeiXin.Service.ServantService.UpdateRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.UpdateRequestBody();
            inValue.Body.entity = entity;
            CorePlus.WeiXin.Service.ServantService.UpdateResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.DeleteResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.Delete(CorePlus.WeiXin.Service.ServantService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(CorePlus.WeiXin.Service.ServantService.ServantInfoEntity entity) {
            CorePlus.WeiXin.Service.ServantService.DeleteRequest inValue = new CorePlus.WeiXin.Service.ServantService.DeleteRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.DeleteRequestBody();
            inValue.Body.entity = entity;
            CorePlus.WeiXin.Service.ServantService.DeleteResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        public bool DeleteById(long id) {
            return base.Channel.DeleteById(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.GetAllResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.GetAll(CorePlus.WeiXin.Service.ServantService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity[] GetAll() {
            CorePlus.WeiXin.Service.ServantService.GetAllRequest inValue = new CorePlus.WeiXin.Service.ServantService.GetAllRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.GetAllRequestBody();
            CorePlus.WeiXin.Service.ServantService.GetAllResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.WeiXin.Service.ServantService.GetByIdResponse CorePlus.WeiXin.Service.ServantService.ServantServiceSoap.GetById(CorePlus.WeiXin.Service.ServantService.GetByIdRequest request) {
            return base.Channel.GetById(request);
        }
        
        public CorePlus.WeiXin.Service.ServantService.ServantInfoEntity GetById(long id) {
            CorePlus.WeiXin.Service.ServantService.GetByIdRequest inValue = new CorePlus.WeiXin.Service.ServantService.GetByIdRequest();
            inValue.Body = new CorePlus.WeiXin.Service.ServantService.GetByIdRequestBody();
            inValue.Body.id = id;
            CorePlus.WeiXin.Service.ServantService.GetByIdResponse retVal = ((CorePlus.WeiXin.Service.ServantService.ServantServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
    }
}
