//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorePlus.P2P.Server.WxAccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CorePlus.P2P.Server.WxAccountService.WxUserEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CorePlus.P2P.Server.WxAccountService.WxAccountEntity))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WxUserEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CorePlus.P2P.Server.WxAccountService.WxAccountEntity))]
    public partial class WxUserEntity : CorePlus.P2P.Server.WxAccountService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WxAccountEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WxAccountEntity : CorePlus.P2P.Server.WxAccountService.WxUserEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrantTypeField;
        
        private System.Nullable<int> ExpiresInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeiXinNoField;
        
        private System.Nullable<int> TokenStatusField;
        
        private bool IsSaveRecordField;
        
        private bool IsAdvancedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIdField, value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Secret {
            get {
                return this.SecretField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretField, value) != true)) {
                    this.SecretField = value;
                    this.RaisePropertyChanged("Secret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GrantType {
            get {
                return this.GrantTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.GrantTypeField, value) != true)) {
                    this.GrantTypeField = value;
                    this.RaisePropertyChanged("GrantType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ExpiresIn {
            get {
                return this.ExpiresInField;
            }
            set {
                if ((this.ExpiresInField.Equals(value) != true)) {
                    this.ExpiresInField = value;
                    this.RaisePropertyChanged("ExpiresIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WeiXinNo {
            get {
                return this.WeiXinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeiXinNoField, value) != true)) {
                    this.WeiXinNoField = value;
                    this.RaisePropertyChanged("WeiXinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> TokenStatus {
            get {
                return this.TokenStatusField;
            }
            set {
                if ((this.TokenStatusField.Equals(value) != true)) {
                    this.TokenStatusField = value;
                    this.RaisePropertyChanged("TokenStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsSaveRecord {
            get {
                return this.IsSaveRecordField;
            }
            set {
                if ((this.IsSaveRecordField.Equals(value) != true)) {
                    this.IsSaveRecordField = value;
                    this.RaisePropertyChanged("IsSaveRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsAdvanced {
            get {
                return this.IsAdvancedField;
            }
            set {
                if ((this.IsAdvancedField.Equals(value) != true)) {
                    this.IsAdvancedField = value;
                    this.RaisePropertyChanged("IsAdvanced");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WxAccountService.WxAccountServiceSoap")]
    public interface WxAccountServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 weixinno 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByWeiXinNo", ReplyAction="*")]
        CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoResponse GetByWeiXinNo(CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        CorePlus.P2P.Server.WxAccountService.AddResponse Add(CorePlus.P2P.Server.WxAccountService.AddRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        CorePlus.P2P.Server.WxAccountService.UpdateResponse Update(CorePlus.P2P.Server.WxAccountService.UpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        CorePlus.P2P.Server.WxAccountService.DeleteResponse Delete(CorePlus.P2P.Server.WxAccountService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteById", ReplyAction="*")]
        bool DeleteById(long id);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        CorePlus.P2P.Server.WxAccountService.GetAllResponse GetAll(CorePlus.P2P.Server.WxAccountService.GetAllRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetByIdResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        CorePlus.P2P.Server.WxAccountService.GetByIdResponse GetById(CorePlus.P2P.Server.WxAccountService.GetByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByWeiXinNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByWeiXinNo", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequestBody Body;
        
        public GetByWeiXinNoRequest() {
        }
        
        public GetByWeiXinNoRequest(CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByWeiXinNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string weixinno;
        
        public GetByWeiXinNoRequestBody() {
        }
        
        public GetByWeiXinNoRequestBody(string weixinno) {
            this.weixinno = weixinno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByWeiXinNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByWeiXinNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoResponseBody Body;
        
        public GetByWeiXinNoResponse() {
        }
        
        public GetByWeiXinNoResponse(CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByWeiXinNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity GetByWeiXinNoResult;
        
        public GetByWeiXinNoResponseBody() {
        }
        
        public GetByWeiXinNoResponseBody(CorePlus.P2P.Server.WxAccountService.WxAccountEntity GetByWeiXinNoResult) {
            this.GetByWeiXinNoResult = GetByWeiXinNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(CorePlus.P2P.Server.WxAccountService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(CorePlus.P2P.Server.WxAccountService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(long AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(CorePlus.P2P.Server.WxAccountService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(CorePlus.P2P.Server.WxAccountService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(CorePlus.P2P.Server.WxAccountService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(CorePlus.P2P.Server.WxAccountService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(bool DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(CorePlus.P2P.Server.WxAccountService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(CorePlus.P2P.Server.WxAccountService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(CorePlus.P2P.Server.WxAccountService.WxAccountEntity[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.GetByIdRequestBody Body;
        
        public GetByIdRequest() {
        }
        
        public GetByIdRequest(CorePlus.P2P.Server.WxAccountService.GetByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetByIdRequestBody() {
        }
        
        public GetByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CorePlus.P2P.Server.WxAccountService.GetByIdResponseBody Body;
        
        public GetByIdResponse() {
        }
        
        public GetByIdResponse(CorePlus.P2P.Server.WxAccountService.GetByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity GetByIdResult;
        
        public GetByIdResponseBody() {
        }
        
        public GetByIdResponseBody(CorePlus.P2P.Server.WxAccountService.WxAccountEntity GetByIdResult) {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WxAccountServiceSoapChannel : CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WxAccountServiceSoapClient : System.ServiceModel.ClientBase<CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap>, CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap {
        
        public WxAccountServiceSoapClient() {
        }
        
        public WxAccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WxAccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WxAccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WxAccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoResponse CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap.GetByWeiXinNo(CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequest request) {
            return base.Channel.GetByWeiXinNo(request);
        }
        
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity GetByWeiXinNo(string weixinno) {
            CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequest inValue = new CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequest();
            inValue.Body = new CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoRequestBody();
            inValue.Body.weixinno = weixinno;
            CorePlus.P2P.Server.WxAccountService.GetByWeiXinNoResponse retVal = ((CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap)(this)).GetByWeiXinNo(inValue);
            return retVal.Body.GetByWeiXinNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.P2P.Server.WxAccountService.AddResponse CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap.Add(CorePlus.P2P.Server.WxAccountService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public long Add(CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity) {
            CorePlus.P2P.Server.WxAccountService.AddRequest inValue = new CorePlus.P2P.Server.WxAccountService.AddRequest();
            inValue.Body = new CorePlus.P2P.Server.WxAccountService.AddRequestBody();
            inValue.Body.entity = entity;
            CorePlus.P2P.Server.WxAccountService.AddResponse retVal = ((CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.P2P.Server.WxAccountService.UpdateResponse CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap.Update(CorePlus.P2P.Server.WxAccountService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity) {
            CorePlus.P2P.Server.WxAccountService.UpdateRequest inValue = new CorePlus.P2P.Server.WxAccountService.UpdateRequest();
            inValue.Body = new CorePlus.P2P.Server.WxAccountService.UpdateRequestBody();
            inValue.Body.entity = entity;
            CorePlus.P2P.Server.WxAccountService.UpdateResponse retVal = ((CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.P2P.Server.WxAccountService.DeleteResponse CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap.Delete(CorePlus.P2P.Server.WxAccountService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(CorePlus.P2P.Server.WxAccountService.WxAccountEntity entity) {
            CorePlus.P2P.Server.WxAccountService.DeleteRequest inValue = new CorePlus.P2P.Server.WxAccountService.DeleteRequest();
            inValue.Body = new CorePlus.P2P.Server.WxAccountService.DeleteRequestBody();
            inValue.Body.entity = entity;
            CorePlus.P2P.Server.WxAccountService.DeleteResponse retVal = ((CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        public bool DeleteById(long id) {
            return base.Channel.DeleteById(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.P2P.Server.WxAccountService.GetAllResponse CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap.GetAll(CorePlus.P2P.Server.WxAccountService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity[] GetAll() {
            CorePlus.P2P.Server.WxAccountService.GetAllRequest inValue = new CorePlus.P2P.Server.WxAccountService.GetAllRequest();
            inValue.Body = new CorePlus.P2P.Server.WxAccountService.GetAllRequestBody();
            CorePlus.P2P.Server.WxAccountService.GetAllResponse retVal = ((CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.P2P.Server.WxAccountService.GetByIdResponse CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap.GetById(CorePlus.P2P.Server.WxAccountService.GetByIdRequest request) {
            return base.Channel.GetById(request);
        }
        
        public CorePlus.P2P.Server.WxAccountService.WxAccountEntity GetById(long id) {
            CorePlus.P2P.Server.WxAccountService.GetByIdRequest inValue = new CorePlus.P2P.Server.WxAccountService.GetByIdRequest();
            inValue.Body = new CorePlus.P2P.Server.WxAccountService.GetByIdRequestBody();
            inValue.Body.id = id;
            CorePlus.P2P.Server.WxAccountService.GetByIdResponse retVal = ((CorePlus.P2P.Server.WxAccountService.WxAccountServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
    }
}
