//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorePlus.API.BaiduAPI_V2_CampaignService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v2", ConfigurationName="BaiduAPI_V2_CampaignService.CampaignService")]
    public interface CampaignService {
        
        // CODEGEN: 消息 getAllCampaignIdRequest 的包装名称(getAllCampaignIdRequest)以后生成的消息协定与默认值(getAllCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CampaignService/getAllCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdResponse getAllCampaignId(CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdRequest request);
        
        // CODEGEN: 消息 getCampaignByCampaignIdRequest 的包装名称(getCampaignByCampaignIdRequest)以后生成的消息协定与默认值(getCampaignByCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CampaignService/getCampaignByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdResponse getCampaignByCampaignId(CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdRequest request);
        
        // CODEGEN: 消息 getAllCampaignRequest 的包装名称(getAllCampaignRequest)以后生成的消息协定与默认值(getAllCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CampaignService/getAllCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignResponse getAllCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignRequest request);
        
        // CODEGEN: 消息 addCampaignRequest 的包装名称(addCampaignRequest)以后生成的消息协定与默认值(addCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CampaignService/addCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignResponse addCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignRequest request);
        
        // CODEGEN: 消息 updateCampaignRequest 的包装名称(updateCampaignRequest)以后生成的消息协定与默认值(updateCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CampaignService/updateCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignResponse updateCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignRequest request);
        
        // CODEGEN: 消息 deleteCampaignRequest 的包装名称(deleteCampaignRequest)以后生成的消息协定与默认值(deleteCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CampaignService/deleteCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignResponse deleteCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class DoubleMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class FloatMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class LongMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class IntMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class StringMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class OptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringMapItemType[] optStringField;
        
        private IntMapItemType[] optIntField;
        
        private LongMapItemType[] optLongField;
        
        private FloatMapItemType[] optFloatField;
        
        private DoubleMapItemType[] optDoubleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optString", Order=0)]
        public StringMapItemType[] optString {
            get {
                return this.optStringField;
            }
            set {
                this.optStringField = value;
                this.RaisePropertyChanged("optString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optInt", Order=1)]
        public IntMapItemType[] optInt {
            get {
                return this.optIntField;
            }
            set {
                this.optIntField = value;
                this.RaisePropertyChanged("optInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optLong", Order=2)]
        public LongMapItemType[] optLong {
            get {
                return this.optLongField;
            }
            set {
                this.optLongField = value;
                this.RaisePropertyChanged("optLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optFloat", Order=3)]
        public FloatMapItemType[] optFloat {
            get {
                return this.optFloatField;
            }
            set {
                this.optFloatField = value;
                this.RaisePropertyChanged("optFloat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optDouble", Order=4)]
        public DoubleMapItemType[] optDouble {
            get {
                return this.optDoubleField;
            }
            set {
                this.optDoubleField = value;
                this.RaisePropertyChanged("optDouble");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class OfflineTimeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int flagField;
        
        private System.DateTime timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class ScheduleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long weekDayField;
        
        private long startHourField;
        
        private long endHourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long weekDay {
            get {
                return this.weekDayField;
            }
            set {
                this.weekDayField = value;
                this.RaisePropertyChanged("weekDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long startHour {
            get {
                return this.startHourField;
            }
            set {
                this.startHourField = value;
                this.RaisePropertyChanged("startHour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long endHour {
            get {
                return this.endHourField;
            }
            set {
                this.endHourField = value;
                this.RaisePropertyChanged("endHour");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class CampaignType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long campaignIdField;
        
        private bool campaignIdFieldSpecified;
        
        private string campaignNameField;
        
        private double budgetField;
        
        private bool budgetFieldSpecified;
        
        private int[] regionTargetField;
        
        private string[] excludeIpField;
        
        private string[] negativeWordsField;
        
        private string[] exactNegativeWordsField;
        
        private ScheduleType[] scheduleField;
        
        private OfflineTimeType[] budgetOfflineTimeField;
        
        private int showProbField;
        
        private bool showProbFieldSpecified;
        
        private bool pauseField;
        
        private bool pauseFieldSpecified;
        
        private bool joinContentField;
        
        private bool joinContentFieldSpecified;
        
        private double contentPriceField;
        
        private bool contentPriceFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool campaignIdSpecified {
            get {
                return this.campaignIdFieldSpecified;
            }
            set {
                this.campaignIdFieldSpecified = value;
                this.RaisePropertyChanged("campaignIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string campaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
                this.RaisePropertyChanged("campaignName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double budget {
            get {
                return this.budgetField;
            }
            set {
                this.budgetField = value;
                this.RaisePropertyChanged("budget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool budgetSpecified {
            get {
                return this.budgetFieldSpecified;
            }
            set {
                this.budgetFieldSpecified = value;
                this.RaisePropertyChanged("budgetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regionTarget", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int[] regionTarget {
            get {
                return this.regionTargetField;
            }
            set {
                this.regionTargetField = value;
                this.RaisePropertyChanged("regionTarget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("excludeIp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string[] excludeIp {
            get {
                return this.excludeIpField;
            }
            set {
                this.excludeIpField = value;
                this.RaisePropertyChanged("excludeIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("negativeWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string[] negativeWords {
            get {
                return this.negativeWordsField;
            }
            set {
                this.negativeWordsField = value;
                this.RaisePropertyChanged("negativeWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exactNegativeWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string[] exactNegativeWords {
            get {
                return this.exactNegativeWordsField;
            }
            set {
                this.exactNegativeWordsField = value;
                this.RaisePropertyChanged("exactNegativeWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("schedule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ScheduleType[] schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
                this.RaisePropertyChanged("schedule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("budgetOfflineTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public OfflineTimeType[] budgetOfflineTime {
            get {
                return this.budgetOfflineTimeField;
            }
            set {
                this.budgetOfflineTimeField = value;
                this.RaisePropertyChanged("budgetOfflineTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int showProb {
            get {
                return this.showProbField;
            }
            set {
                this.showProbField = value;
                this.RaisePropertyChanged("showProb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showProbSpecified {
            get {
                return this.showProbFieldSpecified;
            }
            set {
                this.showProbFieldSpecified = value;
                this.RaisePropertyChanged("showProbSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool pause {
            get {
                return this.pauseField;
            }
            set {
                this.pauseField = value;
                this.RaisePropertyChanged("pause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pauseSpecified {
            get {
                return this.pauseFieldSpecified;
            }
            set {
                this.pauseFieldSpecified = value;
                this.RaisePropertyChanged("pauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool joinContent {
            get {
                return this.joinContentField;
            }
            set {
                this.joinContentField = value;
                this.RaisePropertyChanged("joinContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool joinContentSpecified {
            get {
                return this.joinContentFieldSpecified;
            }
            set {
                this.joinContentFieldSpecified = value;
                this.RaisePropertyChanged("joinContentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double contentPrice {
            get {
                return this.contentPriceField;
            }
            set {
                this.contentPriceField = value;
                this.RaisePropertyChanged("contentPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contentPriceSpecified {
            get {
                return this.contentPriceFieldSpecified;
            }
            set {
                this.contentPriceFieldSpecified = value;
                this.RaisePropertyChanged("contentPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.baidu.com/sem/common/v2", Order=14)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getAllCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader;
        
        public getAllCampaignIdRequest() {
        }
        
        public getAllCampaignIdRequest(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getAllCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getAllCampaignIdResponse() {
        }
        
        public getAllCampaignIdResponse(CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader, long[] campaignIds) {
            this.ResHeader = ResHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignByCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCampaignByCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getCampaignByCampaignIdRequest() {
        }
        
        public getCampaignByCampaignIdRequest(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, long[] campaignIds) {
            this.AuthHeader = AuthHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignByCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCampaignByCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes;
        
        public getCampaignByCampaignIdResponse() {
        }
        
        public getCampaignByCampaignIdResponse(CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getAllCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader;
        
        public getAllCampaignRequest() {
        }
        
        public getAllCampaignRequest(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getAllCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes;
        
        public getAllCampaignResponse() {
        }
        
        public getAllCampaignResponse(CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes;
        
        public addCampaignRequest() {
        }
        
        public addCampaignRequest(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            this.AuthHeader = AuthHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes;
        
        public addCampaignResponse() {
        }
        
        public addCampaignResponse(CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes;
        
        public updateCampaignRequest() {
        }
        
        public updateCampaignRequest(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            this.AuthHeader = AuthHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes;
        
        public updateCampaignResponse() {
        }
        
        public updateCampaignResponse(CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public deleteCampaignRequest() {
        }
        
        public deleteCampaignRequest(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, long[] campaignIds) {
            this.AuthHeader = AuthHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public deleteCampaignResponse() {
        }
        
        public deleteCampaignResponse(CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CampaignServiceChannel : CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampaignServiceClient : System.ServiceModel.ClientBase<CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService>, CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService {
        
        public CampaignServiceClient() {
        }
        
        public CampaignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampaignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdResponse CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService.getAllCampaignId(CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdRequest request) {
            return base.Channel.getAllCampaignId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader getAllCampaignId(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, out long[] campaignIds) {
            CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdRequest inValue = new CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService)(this)).getAllCampaignId(inValue);
            campaignIds = retVal.campaignIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdResponse CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService.getCampaignByCampaignId(CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdRequest request) {
            return base.Channel.getCampaignByCampaignId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader getCampaignByCampaignId(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, long[] campaignIds, out CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdRequest inValue = new CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            CorePlus.API.BaiduAPI_V2_CampaignService.getCampaignByCampaignIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService)(this)).getCampaignByCampaignId(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignResponse CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService.getAllCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignRequest request) {
            return base.Channel.getAllCampaign(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader getAllCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, out CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignRequest inValue = new CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            CorePlus.API.BaiduAPI_V2_CampaignService.getAllCampaignResponse retVal = ((CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService)(this)).getAllCampaign(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignResponse CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService.addCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignRequest request) {
            return base.Channel.addCampaign(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader addCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignRequest inValue = new CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignTypes = campaignTypes;
            CorePlus.API.BaiduAPI_V2_CampaignService.addCampaignResponse retVal = ((CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService)(this)).addCampaign(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignResponse CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService.updateCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignRequest request) {
            return base.Channel.updateCampaign(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader updateCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_CampaignService.CampaignType[] campaignTypes) {
            CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignRequest inValue = new CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignTypes = campaignTypes;
            CorePlus.API.BaiduAPI_V2_CampaignService.updateCampaignResponse retVal = ((CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService)(this)).updateCampaign(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignResponse CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService.deleteCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignRequest request) {
            return base.Channel.deleteCampaign(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CampaignService.ResHeader deleteCampaign(CorePlus.API.BaiduAPI_V2_CampaignService.AuthHeader AuthHeader, long[] campaignIds, out string response) {
            CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignRequest inValue = new CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            CorePlus.API.BaiduAPI_V2_CampaignService.deleteCampaignResponse retVal = ((CorePlus.API.BaiduAPI_V2_CampaignService.CampaignService)(this)).deleteCampaign(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
    }
}
