//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorePlus.API.BaiduAPI_V2_CreativeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v2", ConfigurationName="BaiduAPI_V2_CreativeService.CreativeService")]
    public interface CreativeService {
        
        // CODEGEN: 消息 getCreativeIdByAdgroupIdRequest 的包装名称(getCreativeIdByAdgroupIdRequest)以后生成的消息协定与默认值(getCreativeIdByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/getCreativeIdByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdResponse getCreativeIdByAdgroupId(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getCreativeByAdgroupIdRequest 的包装名称(getCreativeByAdgroupIdRequest)以后生成的消息协定与默认值(getCreativeByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/getCreativeByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdResponse getCreativeByAdgroupId(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getCreativeByCreativeIdRequest 的包装名称(getCreativeByCreativeIdRequest)以后生成的消息协定与默认值(getCreativeByCreativeId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/getCreativeByCreativeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdResponse getCreativeByCreativeId(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdRequest request);
        
        // CODEGEN: 消息 addCreativeRequest 的包装名称(addCreativeRequest)以后生成的消息协定与默认值(addCreative)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/addCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeResponse addCreative(CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeRequest request);
        
        // CODEGEN: 消息 updateCreativeRequest 的包装名称(updateCreativeRequest)以后生成的消息协定与默认值(updateCreative)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/updateCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeResponse updateCreative(CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeRequest request);
        
        // CODEGEN: 消息 deleteCreativeRequest 的包装名称(deleteCreativeRequest)以后生成的消息协定与默认值(deleteCreative)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/deleteCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeResponse deleteCreative(CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeRequest request);
        
        // CODEGEN: 消息 activateCreativeRequest 的包装名称(activateCreativeRequest)以后生成的消息协定与默认值(activateCreative)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/activateCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeResponse activateCreative(CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeRequest request);
        
        // CODEGEN: 消息 getCreativeStatusRequest 的包装名称(getCreativeStatusRequest)以后生成的消息协定与默认值(getCreativeStatus)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/getCreativeStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusResponse getCreativeStatus(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusRequest request);
        
        // CODEGEN: 消息 getCreativeStatusZipRequest 的包装名称(getCreativeStatusZipRequest)以后生成的消息协定与默认值(getCreativeStatusZip)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/CreativeService/getCreativeStatusZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipResponse getCreativeStatusZip(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private long adgroupIdField;
        
        private long campaignIdField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class DoubleMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class FloatMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class LongMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class IntMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class StringMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class OptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringMapItemType[] optStringField;
        
        private IntMapItemType[] optIntField;
        
        private LongMapItemType[] optLongField;
        
        private FloatMapItemType[] optFloatField;
        
        private DoubleMapItemType[] optDoubleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optString", Order=0)]
        public StringMapItemType[] optString {
            get {
                return this.optStringField;
            }
            set {
                this.optStringField = value;
                this.RaisePropertyChanged("optString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optInt", Order=1)]
        public IntMapItemType[] optInt {
            get {
                return this.optIntField;
            }
            set {
                this.optIntField = value;
                this.RaisePropertyChanged("optInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optLong", Order=2)]
        public LongMapItemType[] optLong {
            get {
                return this.optLongField;
            }
            set {
                this.optLongField = value;
                this.RaisePropertyChanged("optLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optFloat", Order=3)]
        public FloatMapItemType[] optFloat {
            get {
                return this.optFloatField;
            }
            set {
                this.optFloatField = value;
                this.RaisePropertyChanged("optFloat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optDouble", Order=4)]
        public DoubleMapItemType[] optDouble {
            get {
                return this.optDoubleField;
            }
            set {
                this.optDoubleField = value;
                this.RaisePropertyChanged("optDouble");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class CreativeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long creativeIdField;
        
        private bool creativeIdFieldSpecified;
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private string titleField;
        
        private string description1Field;
        
        private string description2Field;
        
        private string destinationUrlField;
        
        private string displayUrlField;
        
        private bool pauseField;
        
        private bool pauseFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long creativeId {
            get {
                return this.creativeIdField;
            }
            set {
                this.creativeIdField = value;
                this.RaisePropertyChanged("creativeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creativeIdSpecified {
            get {
                return this.creativeIdFieldSpecified;
            }
            set {
                this.creativeIdFieldSpecified = value;
                this.RaisePropertyChanged("creativeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description1 {
            get {
                return this.description1Field;
            }
            set {
                this.description1Field = value;
                this.RaisePropertyChanged("description1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string description2 {
            get {
                return this.description2Field;
            }
            set {
                this.description2Field = value;
                this.RaisePropertyChanged("description2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string destinationUrl {
            get {
                return this.destinationUrlField;
            }
            set {
                this.destinationUrlField = value;
                this.RaisePropertyChanged("destinationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string displayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
                this.RaisePropertyChanged("displayUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool pause {
            get {
                return this.pauseField;
            }
            set {
                this.pauseField = value;
                this.RaisePropertyChanged("pause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pauseSpecified {
            get {
                return this.pauseFieldSpecified;
            }
            set {
                this.pauseFieldSpecified = value;
                this.RaisePropertyChanged("pauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.baidu.com/sem/common/v2", Order=9)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class GroupCreative : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private CreativeType[] creativeTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CreativeType[] creativeTypes {
            get {
                return this.creativeTypesField;
            }
            set {
                this.creativeTypesField = value;
                this.RaisePropertyChanged("creativeTypes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class GroupCreativeId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private long[] creativeIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long[] creativeIds {
            get {
                return this.creativeIdsField;
            }
            set {
                this.creativeIdsField = value;
                this.RaisePropertyChanged("creativeIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeIdByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeIdByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getCreativeIdByAdgroupIdRequest() {
        }
        
        public getCreativeIdByAdgroupIdRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeIdByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeIdByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupCreativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.GroupCreativeId[] groupCreativeIds;
        
        public getCreativeIdByAdgroupIdResponse() {
        }
        
        public getCreativeIdByAdgroupIdResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.GroupCreativeId[] groupCreativeIds) {
            this.ResHeader = ResHeader;
            this.groupCreativeIds = groupCreativeIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getCreativeByAdgroupIdRequest() {
        }
        
        public getCreativeByAdgroupIdRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupCreatives", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.GroupCreative[] groupCreatives;
        
        public getCreativeByAdgroupIdResponse() {
        }
        
        public getCreativeByAdgroupIdResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.GroupCreative[] groupCreatives) {
            this.ResHeader = ResHeader;
            this.groupCreatives = groupCreatives;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByCreativeIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeByCreativeIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] creativeIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getCreativeByCreativeIdRequest() {
        }
        
        public getCreativeByCreativeIdRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] creativeIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.creativeIds = creativeIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByCreativeIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeByCreativeIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes;
        
        public getCreativeByCreativeIdResponse() {
        }
        
        public getCreativeByCreativeIdResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes;
        
        public addCreativeRequest() {
        }
        
        public addCreativeRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            this.AuthHeader = AuthHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes;
        
        public addCreativeResponse() {
        }
        
        public addCreativeResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes;
        
        public updateCreativeRequest() {
        }
        
        public updateCreativeRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            this.AuthHeader = AuthHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes;
        
        public updateCreativeResponse() {
        }
        
        public updateCreativeResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] creativeIds;
        
        public deleteCreativeRequest() {
        }
        
        public deleteCreativeRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] creativeIds) {
            this.AuthHeader = AuthHeader;
            this.creativeIds = creativeIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public deleteCreativeResponse() {
        }
        
        public deleteCreativeResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class activateCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] creativeIds;
        
        public activateCreativeRequest() {
        }
        
        public activateCreativeRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] creativeIds) {
            this.AuthHeader = AuthHeader;
            this.creativeIds = creativeIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class activateCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes;
        
        public activateCreativeResponse() {
        }
        
        public activateCreativeResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getCreativeStatusRequest() {
        }
        
        public getCreativeStatusRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_CreativeService.StatusType[] creativeStatus;
        
        public getCreativeStatusResponse() {
        }
        
        public getCreativeStatusResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_CreativeService.StatusType[] creativeStatus) {
            this.ResHeader = ResHeader;
            this.creativeStatus = creativeStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusZipRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeStatusZipRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getCreativeStatusZipRequest() {
        }
        
        public getCreativeStatusZipRequest(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusZipResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getCreativeStatusZipResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] creativeStatus;
        
        public getCreativeStatusZipResponse() {
        }
        
        public getCreativeStatusZipResponse(CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader ResHeader, byte[] creativeStatus) {
            this.ResHeader = ResHeader;
            this.creativeStatus = creativeStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreativeServiceChannel : CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreativeServiceClient : System.ServiceModel.ClientBase<CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService>, CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService {
        
        public CreativeServiceClient() {
        }
        
        public CreativeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreativeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreativeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreativeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.getCreativeIdByAdgroupId(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdRequest request) {
            return base.Channel.getCreativeIdByAdgroupId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader getCreativeIdByAdgroupId(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out CorePlus.API.BaiduAPI_V2_CreativeService.GroupCreativeId[] groupCreativeIds) {
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeIdByAdgroupIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).getCreativeIdByAdgroupId(inValue);
            groupCreativeIds = retVal.groupCreativeIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.getCreativeByAdgroupId(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdRequest request) {
            return base.Channel.getCreativeByAdgroupId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader getCreativeByAdgroupId(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out CorePlus.API.BaiduAPI_V2_CreativeService.GroupCreative[] groupCreatives) {
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByAdgroupIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).getCreativeByAdgroupId(inValue);
            groupCreatives = retVal.groupCreatives;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.getCreativeByCreativeId(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdRequest request) {
            return base.Channel.getCreativeByCreativeId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader getCreativeByCreativeId(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] creativeIds, int getTemp, out CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeByCreativeIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).getCreativeByCreativeId(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.addCreative(CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeRequest request) {
            return base.Channel.addCreative(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader addCreative(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeTypes = creativeTypes;
            CorePlus.API.BaiduAPI_V2_CreativeService.addCreativeResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).addCreative(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.updateCreative(CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeRequest request) {
            return base.Channel.updateCreative(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader updateCreative(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeTypes = creativeTypes;
            CorePlus.API.BaiduAPI_V2_CreativeService.updateCreativeResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).updateCreative(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.deleteCreative(CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeRequest request) {
            return base.Channel.deleteCreative(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader deleteCreative(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] creativeIds, out string response) {
            CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            CorePlus.API.BaiduAPI_V2_CreativeService.deleteCreativeResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).deleteCreative(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.activateCreative(CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeRequest request) {
            return base.Channel.activateCreative(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader activateCreative(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] creativeIds, out CorePlus.API.BaiduAPI_V2_CreativeService.CreativeType[] creativeTypes) {
            CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            CorePlus.API.BaiduAPI_V2_CreativeService.activateCreativeResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).activateCreative(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.getCreativeStatus(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusRequest request) {
            return base.Channel.getCreativeStatus(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader getCreativeStatus(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] ids, int type, out CorePlus.API.BaiduAPI_V2_CreativeService.StatusType[] creativeStatus) {
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).getCreativeStatus(inValue);
            creativeStatus = retVal.creativeStatus;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipResponse CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService.getCreativeStatusZip(CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipRequest request) {
            return base.Channel.getCreativeStatusZip(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_CreativeService.ResHeader getCreativeStatusZip(CorePlus.API.BaiduAPI_V2_CreativeService.AuthHeader AuthHeader, long[] ids, int type, out byte[] creativeStatus) {
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipRequest inValue = new CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            CorePlus.API.BaiduAPI_V2_CreativeService.getCreativeStatusZipResponse retVal = ((CorePlus.API.BaiduAPI_V2_CreativeService.CreativeService)(this)).getCreativeStatusZip(inValue);
            creativeStatus = retVal.creativeStatus;
            return retVal.ResHeader;
        }
    }
}
