//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorePlus.API.BaiduAPI_V2_NewCreativeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v2", ConfigurationName="BaiduAPI_V2_NewCreativeService.NewCreativeService")]
    public interface NewCreativeService {
        
        // CODEGEN: 消息 getSublinkIdByAdgroupIdRequest 的包装名称(GetSublinkIdByAdgroupIdRequest)以后生成的消息协定与默认值(getSublinkIdByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/NewCreativeService/getSublinkIdByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdResponse getSublinkIdByAdgroupId(CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getSublinkBySublinkIdRequest 的包装名称(GetSublinkBySublinkIdRequest)以后生成的消息协定与默认值(getSublinkBySublinkId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/NewCreativeService/getSublinkBySublinkId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdResponse getSublinkBySublinkId(CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdRequest request);
        
        // CODEGEN: 消息 addSublinkRequest 的包装名称(AddSublinkRequest)以后生成的消息协定与默认值(addSublink)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/NewCreativeService/addSublink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkResponse addSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkRequest request);
        
        // CODEGEN: 消息 updateSublinkRequest 的包装名称(UpdateSublinkRequest)以后生成的消息协定与默认值(updateSublink)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/NewCreativeService/updateSublink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkResponse updateSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkRequest request);
        
        // CODEGEN: 消息 deleteSublinkRequest 的包装名称(DeleteSublinkRequest)以后生成的消息协定与默认值(deleteSublink)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/NewCreativeService/deleteSublink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkResponse deleteSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class SublinkInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string destinationUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string destinationUrl {
            get {
                return this.destinationUrlField;
            }
            set {
                this.destinationUrlField = value;
                this.RaisePropertyChanged("destinationUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class SublinkType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long sublinkIdField;
        
        private bool sublinkIdFieldSpecified;
        
        private SublinkInfo[] sublinkInfosField;
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private bool pauseField;
        
        private bool pauseFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long sublinkId {
            get {
                return this.sublinkIdField;
            }
            set {
                this.sublinkIdField = value;
                this.RaisePropertyChanged("sublinkId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sublinkIdSpecified {
            get {
                return this.sublinkIdFieldSpecified;
            }
            set {
                this.sublinkIdFieldSpecified = value;
                this.RaisePropertyChanged("sublinkIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sublinkInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SublinkInfo[] sublinkInfos {
            get {
                return this.sublinkInfosField;
            }
            set {
                this.sublinkInfosField = value;
                this.RaisePropertyChanged("sublinkInfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool pause {
            get {
                return this.pauseField;
            }
            set {
                this.pauseField = value;
                this.RaisePropertyChanged("pause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pauseSpecified {
            get {
                return this.pauseFieldSpecified;
            }
            set {
                this.pauseFieldSpecified = value;
                this.RaisePropertyChanged("pauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class GroupSublinkId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private long[] sublinkIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sublinkIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long[] sublinkIds {
            get {
                return this.sublinkIdsField;
            }
            set {
                this.sublinkIdsField = value;
                this.RaisePropertyChanged("sublinkIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSublinkIdByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getSublinkIdByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getSublinkIdByAdgroupIdRequest() {
        }
        
        public getSublinkIdByAdgroupIdRequest(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSublinkIdByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getSublinkIdByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupSublinkIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.GroupSublinkId[] groupSublinkIds;
        
        public getSublinkIdByAdgroupIdResponse() {
        }
        
        public getSublinkIdByAdgroupIdResponse(CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_NewCreativeService.GroupSublinkId[] groupSublinkIds) {
            this.ResHeader = ResHeader;
            this.groupSublinkIds = groupSublinkIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSublinkBySublinkIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getSublinkBySublinkIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] sublinkIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getSublinkBySublinkIdRequest() {
        }
        
        public getSublinkBySublinkIdRequest(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, long[] sublinkIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.sublinkIds = sublinkIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSublinkBySublinkIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getSublinkBySublinkIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes;
        
        public getSublinkBySublinkIdResponse() {
        }
        
        public getSublinkBySublinkIdResponse(CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            this.ResHeader = ResHeader;
            this.sublinkTypes = sublinkTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSublinkRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addSublinkRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes;
        
        public addSublinkRequest() {
        }
        
        public addSublinkRequest(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            this.AuthHeader = AuthHeader;
            this.sublinkTypes = sublinkTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSublinkResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addSublinkResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes;
        
        public addSublinkResponse() {
        }
        
        public addSublinkResponse(CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            this.ResHeader = ResHeader;
            this.sublinkTypes = sublinkTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSublinkRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateSublinkRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes;
        
        public updateSublinkRequest() {
        }
        
        public updateSublinkRequest(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            this.AuthHeader = AuthHeader;
            this.sublinkTypes = sublinkTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSublinkResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateSublinkResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes;
        
        public updateSublinkResponse() {
        }
        
        public updateSublinkResponse(CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            this.ResHeader = ResHeader;
            this.sublinkTypes = sublinkTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSublinkRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteSublinkRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sublinkIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] sublinkIds;
        
        public deleteSublinkRequest() {
        }
        
        public deleteSublinkRequest(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, long[] sublinkIds) {
            this.AuthHeader = AuthHeader;
            this.sublinkIds = sublinkIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSublinkResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteSublinkResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int optResult;
        
        public deleteSublinkResponse() {
        }
        
        public deleteSublinkResponse(CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader ResHeader, int optResult) {
            this.ResHeader = ResHeader;
            this.optResult = optResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewCreativeServiceChannel : CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewCreativeServiceClient : System.ServiceModel.ClientBase<CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService>, CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService {
        
        public NewCreativeServiceClient() {
        }
        
        public NewCreativeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewCreativeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewCreativeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewCreativeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdResponse CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService.getSublinkIdByAdgroupId(CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdRequest request) {
            return base.Channel.getSublinkIdByAdgroupId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader getSublinkIdByAdgroupId(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out CorePlus.API.BaiduAPI_V2_NewCreativeService.GroupSublinkId[] groupSublinkIds) {
            CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdRequest inValue = new CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkIdByAdgroupIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService)(this)).getSublinkIdByAdgroupId(inValue);
            groupSublinkIds = retVal.groupSublinkIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdResponse CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService.getSublinkBySublinkId(CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdRequest request) {
            return base.Channel.getSublinkBySublinkId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader getSublinkBySublinkId(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, long[] sublinkIds, int getTemp, out CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdRequest inValue = new CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.sublinkIds = sublinkIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_NewCreativeService.getSublinkBySublinkIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService)(this)).getSublinkBySublinkId(inValue);
            sublinkTypes = retVal.sublinkTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkResponse CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService.addSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkRequest request) {
            return base.Channel.addSublink(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader addSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkRequest inValue = new CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.sublinkTypes = sublinkTypes;
            CorePlus.API.BaiduAPI_V2_NewCreativeService.addSublinkResponse retVal = ((CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService)(this)).addSublink(inValue);
            sublinkTypes = retVal.sublinkTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkResponse CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService.updateSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkRequest request) {
            return base.Channel.updateSublink(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader updateSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_NewCreativeService.SublinkType[] sublinkTypes) {
            CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkRequest inValue = new CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.sublinkTypes = sublinkTypes;
            CorePlus.API.BaiduAPI_V2_NewCreativeService.updateSublinkResponse retVal = ((CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService)(this)).updateSublink(inValue);
            sublinkTypes = retVal.sublinkTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkResponse CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService.deleteSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkRequest request) {
            return base.Channel.deleteSublink(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_NewCreativeService.ResHeader deleteSublink(CorePlus.API.BaiduAPI_V2_NewCreativeService.AuthHeader AuthHeader, long[] sublinkIds, out int optResult) {
            CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkRequest inValue = new CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.sublinkIds = sublinkIds;
            CorePlus.API.BaiduAPI_V2_NewCreativeService.deleteSublinkResponse retVal = ((CorePlus.API.BaiduAPI_V2_NewCreativeService.NewCreativeService)(this)).deleteSublink(inValue);
            optResult = retVal.optResult;
            return retVal.ResHeader;
        }
    }
}
