//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorePlus.API.BaiduAPI_V2_KeywordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v2", ConfigurationName="BaiduAPI_V2_KeywordService.KeywordService")]
    public interface KeywordService {
        
        // CODEGEN: 消息 getKeywordIdByAdgroupIdRequest 的包装名称(getKeywordIdByAdgroupIdRequest)以后生成的消息协定与默认值(getKeywordIdByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordIdByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdResponse getKeywordIdByAdgroupId(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getKeywordByAdgroupIdRequest 的包装名称(getKeywordByAdgroupIdRequest)以后生成的消息协定与默认值(getKeywordByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdResponse getKeywordByAdgroupId(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getKeywordByKeywordIdRequest 的包装名称(getKeywordByKeywordIdRequest)以后生成的消息协定与默认值(getKeywordByKeywordId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordByKeywordId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdResponse getKeywordByKeywordId(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdRequest request);
        
        // CODEGEN: 消息 addKeywordRequest 的包装名称(addKeywordRequest)以后生成的消息协定与默认值(addKeyword)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/addKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordResponse addKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordRequest request);
        
        // CODEGEN: 消息 updateKeywordRequest 的包装名称(updateKeywordRequest)以后生成的消息协定与默认值(updateKeyword)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/updateKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordResponse updateKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordRequest request);
        
        // CODEGEN: 消息 deleteKeywordRequest 的包装名称(deleteKeywordRequest)以后生成的消息协定与默认值(deleteKeyword)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/deleteKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordResponse deleteKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordRequest request);
        
        // CODEGEN: 消息 activateKeywordRequest 的包装名称(activateKeywordRequest)以后生成的消息协定与默认值(activateKeyword)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/activateKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordResponse activateKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordRequest request);
        
        // CODEGEN: 消息 getKeywordStatusRequest 的包装名称(getKeywordStatusRequest)以后生成的消息协定与默认值(getKeywordStatus)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusResponse getKeywordStatus(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusRequest request);
        
        // CODEGEN: 消息 getKeywordStatusZipRequest 的包装名称(getKeywordStatusZipRequest)以后生成的消息协定与默认值(getKeywordStatusZip)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordStatusZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipResponse getKeywordStatusZip(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipRequest request);
        
        // CODEGEN: 消息 getKeywordQualityRequest 的包装名称(getKeywordQualityRequest)以后生成的消息协定与默认值(getKeywordQuality)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordQuality", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityResponse getKeywordQuality(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityRequest request);
        
        // CODEGEN: 消息 getKeywordQualityZipRequest 的包装名称(getKeywordQualityZipRequest)以后生成的消息协定与默认值(getKeywordQualityZip)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v2/KeywordService/getKeywordQualityZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipResponse getKeywordQualityZip(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class QualityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private long adgroupIdField;
        
        private long campaignIdField;
        
        private int qualityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
                this.RaisePropertyChanged("quality");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private long adgroupIdField;
        
        private long campaignIdField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class DoubleMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class FloatMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class LongMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class IntMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class StringMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class OptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringMapItemType[] optStringField;
        
        private IntMapItemType[] optIntField;
        
        private LongMapItemType[] optLongField;
        
        private FloatMapItemType[] optFloatField;
        
        private DoubleMapItemType[] optDoubleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optString", Order=0)]
        public StringMapItemType[] optString {
            get {
                return this.optStringField;
            }
            set {
                this.optStringField = value;
                this.RaisePropertyChanged("optString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optInt", Order=1)]
        public IntMapItemType[] optInt {
            get {
                return this.optIntField;
            }
            set {
                this.optIntField = value;
                this.RaisePropertyChanged("optInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optLong", Order=2)]
        public LongMapItemType[] optLong {
            get {
                return this.optLongField;
            }
            set {
                this.optLongField = value;
                this.RaisePropertyChanged("optLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optFloat", Order=3)]
        public FloatMapItemType[] optFloat {
            get {
                return this.optFloatField;
            }
            set {
                this.optFloatField = value;
                this.RaisePropertyChanged("optFloat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optDouble", Order=4)]
        public DoubleMapItemType[] optDouble {
            get {
                return this.optDoubleField;
            }
            set {
                this.optDoubleField = value;
                this.RaisePropertyChanged("optDouble");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class KeywordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long keywordIdField;
        
        private bool keywordIdFieldSpecified;
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private string keywordField;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private string destinationUrlField;
        
        private int matchTypeField;
        
        private bool matchTypeFieldSpecified;
        
        private bool pauseField;
        
        private bool pauseFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long keywordId {
            get {
                return this.keywordIdField;
            }
            set {
                this.keywordIdField = value;
                this.RaisePropertyChanged("keywordId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keywordIdSpecified {
            get {
                return this.keywordIdFieldSpecified;
            }
            set {
                this.keywordIdFieldSpecified = value;
                this.RaisePropertyChanged("keywordIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
                this.RaisePropertyChanged("keyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string destinationUrl {
            get {
                return this.destinationUrlField;
            }
            set {
                this.destinationUrlField = value;
                this.RaisePropertyChanged("destinationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int matchType {
            get {
                return this.matchTypeField;
            }
            set {
                this.matchTypeField = value;
                this.RaisePropertyChanged("matchType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool matchTypeSpecified {
            get {
                return this.matchTypeFieldSpecified;
            }
            set {
                this.matchTypeFieldSpecified = value;
                this.RaisePropertyChanged("matchTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool pause {
            get {
                return this.pauseField;
            }
            set {
                this.pauseField = value;
                this.RaisePropertyChanged("pause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pauseSpecified {
            get {
                return this.pauseFieldSpecified;
            }
            set {
                this.pauseFieldSpecified = value;
                this.RaisePropertyChanged("pauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.baidu.com/sem/common/v2", Order=8)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class GroupKeyword : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private KeywordType[] keywordTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public KeywordType[] keywordTypes {
            get {
                return this.keywordTypesField;
            }
            set {
                this.keywordTypesField = value;
                this.RaisePropertyChanged("keywordTypes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v2")]
    public partial class GroupKeywordId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private long[] keywordIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywordIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long[] keywordIds {
            get {
                return this.keywordIdsField;
            }
            set {
                this.keywordIdsField = value;
                this.RaisePropertyChanged("keywordIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordIdByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordIdByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getKeywordIdByAdgroupIdRequest() {
        }
        
        public getKeywordIdByAdgroupIdRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordIdByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordIdByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupKeywordIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.GroupKeywordId[] groupKeywordIds;
        
        public getKeywordIdByAdgroupIdResponse() {
        }
        
        public getKeywordIdByAdgroupIdResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.GroupKeywordId[] groupKeywordIds) {
            this.ResHeader = ResHeader;
            this.groupKeywordIds = groupKeywordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getKeywordByAdgroupIdRequest() {
        }
        
        public getKeywordByAdgroupIdRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupKeywords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.GroupKeyword[] groupKeywords;
        
        public getKeywordByAdgroupIdResponse() {
        }
        
        public getKeywordByAdgroupIdResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.GroupKeyword[] groupKeywords) {
            this.ResHeader = ResHeader;
            this.groupKeywords = groupKeywords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordByKeywordIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordByKeywordIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] keywordIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getKeywordByKeywordIdRequest() {
        }
        
        public getKeywordByKeywordIdRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] keywordIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.keywordIds = keywordIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordByKeywordIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordByKeywordIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes;
        
        public getKeywordByKeywordIdResponse() {
        }
        
        public getKeywordByKeywordIdResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            this.ResHeader = ResHeader;
            this.keywordTypes = keywordTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addKeywordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addKeywordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes;
        
        public addKeywordRequest() {
        }
        
        public addKeywordRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            this.AuthHeader = AuthHeader;
            this.keywordTypes = keywordTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addKeywordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class addKeywordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes;
        
        public addKeywordResponse() {
        }
        
        public addKeywordResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            this.ResHeader = ResHeader;
            this.keywordTypes = keywordTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateKeywordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateKeywordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes;
        
        public updateKeywordRequest() {
        }
        
        public updateKeywordRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            this.AuthHeader = AuthHeader;
            this.keywordTypes = keywordTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateKeywordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class updateKeywordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes;
        
        public updateKeywordResponse() {
        }
        
        public updateKeywordResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            this.ResHeader = ResHeader;
            this.keywordTypes = keywordTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteKeywordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteKeywordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] keywordIds;
        
        public deleteKeywordRequest() {
        }
        
        public deleteKeywordRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] keywordIds) {
            this.AuthHeader = AuthHeader;
            this.keywordIds = keywordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteKeywordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class deleteKeywordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public deleteKeywordResponse() {
        }
        
        public deleteKeywordResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateKeywordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class activateKeywordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] keywordIds;
        
        public activateKeywordRequest() {
        }
        
        public activateKeywordRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] keywordIds) {
            this.AuthHeader = AuthHeader;
            this.keywordIds = keywordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateKeywordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class activateKeywordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes;
        
        public activateKeywordResponse() {
        }
        
        public activateKeywordResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            this.ResHeader = ResHeader;
            this.keywordTypes = keywordTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordStatusRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getKeywordStatusRequest() {
        }
        
        public getKeywordStatusRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordStatusResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("keywordStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.StatusType[] keywordStatus;
        
        public getKeywordStatusResponse() {
        }
        
        public getKeywordStatusResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.StatusType[] keywordStatus) {
            this.ResHeader = ResHeader;
            this.keywordStatus = keywordStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordStatusZipRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordStatusZipRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getKeywordStatusZipRequest() {
        }
        
        public getKeywordStatusZipRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordStatusZipResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordStatusZipResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] keywordStatus;
        
        public getKeywordStatusZipResponse() {
        }
        
        public getKeywordStatusZipResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, byte[] keywordStatus) {
            this.ResHeader = ResHeader;
            this.keywordStatus = keywordStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordQualityRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordQualityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getKeywordQualityRequest() {
        }
        
        public getKeywordQualityRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordQualityResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordQualityResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("qualities", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorePlus.API.BaiduAPI_V2_KeywordService.QualityType[] qualities;
        
        public getKeywordQualityResponse() {
        }
        
        public getKeywordQualityResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, CorePlus.API.BaiduAPI_V2_KeywordService.QualityType[] qualities) {
            this.ResHeader = ResHeader;
            this.qualities = qualities;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordQualityZipRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordQualityZipRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getKeywordQualityZipRequest() {
        }
        
        public getKeywordQualityZipRequest(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKeywordQualityZipResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v2", IsWrapped=true)]
    public partial class getKeywordQualityZipResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] qualities;
        
        public getKeywordQualityZipResponse() {
        }
        
        public getKeywordQualityZipResponse(CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader ResHeader, byte[] qualities) {
            this.ResHeader = ResHeader;
            this.qualities = qualities;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeywordServiceChannel : CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeywordServiceClient : System.ServiceModel.ClientBase<CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService>, CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService {
        
        public KeywordServiceClient() {
        }
        
        public KeywordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeywordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordIdByAdgroupId(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdRequest request) {
            return base.Channel.getKeywordIdByAdgroupId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordIdByAdgroupId(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out CorePlus.API.BaiduAPI_V2_KeywordService.GroupKeywordId[] groupKeywordIds) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordIdByAdgroupIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordIdByAdgroupId(inValue);
            groupKeywordIds = retVal.groupKeywordIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordByAdgroupId(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdRequest request) {
            return base.Channel.getKeywordByAdgroupId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordByAdgroupId(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out CorePlus.API.BaiduAPI_V2_KeywordService.GroupKeyword[] groupKeywords) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByAdgroupIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordByAdgroupId(inValue);
            groupKeywords = retVal.groupKeywords;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordByKeywordId(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdRequest request) {
            return base.Channel.getKeywordByKeywordId(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordByKeywordId(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] keywordIds, int getTemp, out CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.keywordIds = keywordIds;
            inValue.getTemp = getTemp;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordByKeywordIdResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordByKeywordId(inValue);
            keywordTypes = retVal.keywordTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.addKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordRequest request) {
            return base.Channel.addKeyword(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader addKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.keywordTypes = keywordTypes;
            CorePlus.API.BaiduAPI_V2_KeywordService.addKeywordResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).addKeyword(inValue);
            keywordTypes = retVal.keywordTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.updateKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordRequest request) {
            return base.Channel.updateKeyword(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader updateKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, ref CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.keywordTypes = keywordTypes;
            CorePlus.API.BaiduAPI_V2_KeywordService.updateKeywordResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).updateKeyword(inValue);
            keywordTypes = retVal.keywordTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.deleteKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordRequest request) {
            return base.Channel.deleteKeyword(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader deleteKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] keywordIds, out string response) {
            CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.keywordIds = keywordIds;
            CorePlus.API.BaiduAPI_V2_KeywordService.deleteKeywordResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).deleteKeyword(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.activateKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordRequest request) {
            return base.Channel.activateKeyword(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader activateKeyword(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] keywordIds, out CorePlus.API.BaiduAPI_V2_KeywordService.KeywordType[] keywordTypes) {
            CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.keywordIds = keywordIds;
            CorePlus.API.BaiduAPI_V2_KeywordService.activateKeywordResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).activateKeyword(inValue);
            keywordTypes = retVal.keywordTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordStatus(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusRequest request) {
            return base.Channel.getKeywordStatus(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordStatus(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type, out CorePlus.API.BaiduAPI_V2_KeywordService.StatusType[] keywordStatus) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordStatus(inValue);
            keywordStatus = retVal.keywordStatus;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordStatusZip(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipRequest request) {
            return base.Channel.getKeywordStatusZip(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordStatusZip(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type, out byte[] keywordStatus) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordStatusZipResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordStatusZip(inValue);
            keywordStatus = retVal.keywordStatus;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordQuality(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityRequest request) {
            return base.Channel.getKeywordQuality(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordQuality(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type, out CorePlus.API.BaiduAPI_V2_KeywordService.QualityType[] qualities) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordQuality(inValue);
            qualities = retVal.qualities;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipResponse CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService.getKeywordQualityZip(CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipRequest request) {
            return base.Channel.getKeywordQualityZip(request);
        }
        
        public CorePlus.API.BaiduAPI_V2_KeywordService.ResHeader getKeywordQualityZip(CorePlus.API.BaiduAPI_V2_KeywordService.AuthHeader AuthHeader, long[] ids, int type, out byte[] qualities) {
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipRequest inValue = new CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            CorePlus.API.BaiduAPI_V2_KeywordService.getKeywordQualityZipResponse retVal = ((CorePlus.API.BaiduAPI_V2_KeywordService.KeywordService)(this)).getKeywordQualityZip(inValue);
            qualities = retVal.qualities;
            return retVal.ResHeader;
        }
    }
}
